---
- name: update web server 
  hosts: all
  become: yes

  tasks:
  - name: install apache
    yum:
      name: httpd
      state: present

  - name: start apache
    service:
      name: httpd
      state: started

  - name: enable apache
    service:
      name: httpd
      enabled: yes
...
